test_db_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views



app_name = 'test_db_app'

urlpatterns = [
    url(r'^$', views.index, name='index' ),
    path("<str:productId>", views.detail, name="detail"),
    path("<str:productId>/favorite", views.favorite, name="favorite"),
]

test_db_website/urls.py
from django.urls import path
from django.conf.urls import include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('test_db_app/', include('test_db_app.urls')),
]

test_db_app/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    productName = models.CharField(max_length=255)
    productType = models.CharField(max_length = 255, default="give type")
    
    def __str__(self):
        return self.productName

class Batch(models.Model):
    batchNumber = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    is_favorite = models.BooleanField(default =False)
    
    def __str__(self):
        return str(self.batchNumber)

class MachineUsers(models.Model):
    userName = models.CharField(max_length=255)
    userType = models.CharField(max_length=255)

test_db_app/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import Http404
from .models import Product, Batch


def index(request):
    all_products = Product.objects.all()
    context = {'all_products': all_products,}
    return render(request, "products/index.html", context)


def detail(request, productId):
    # product = Product.objects.get(pk=productId)    
    #except Product.DoesNotExist:
    #raise Http404("Product does not exist")
    
    product = get_object_or_404(Product,pk=productId)
    
    context = {"product":product}
    return render(request, "products/product.html", context)


def favorite(request, productId):
    product = get_object_or_404(Product,pk=productId)
    
    try:
        selectedBatch = product.batch_set.get(pk=request.POST['batch'])
    except(KeyError, Batch.DoesNotExist):
        return render(request, "products/product.html", {
            "product": product,
            'error_message': 'YOU DID NOT SELECT A BATCH...',
            })
    else:
        selectedBatch.is_favorite = True
        selectedBatch.save()
    return render(request, "products/product.html", { "product": product })
    

"""
html =''
for product in all_products:
    url = "/test_db_app/" +str(product.id)
    html += "<a href='"+ url +"'>"+product.productName+"</a><br>"

"""

test_db_app/templates/products/index.html
{% if all_products %}
    <ul>
        {% for product in all_products %}
        <li><a href="{% url 'test_db_app:detail' product.pk %}">{{ product.productName }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>There are no products available.</h3>
{% endif %}

test_db_app/templates/products/product.html
<h2>The product name is: {{ product.productName }} </h2>

<h2>The product type is: {{ product.productType }}</h2>

{% if error_message %}
    <p><strong>{{ error_message }} </strong></p>
{% endif %}

<form action="{% url 'test_db_app:favorite' product.pk %}" method="POST">
    {% csrf_token %}
    {% for batch in product.batch_set.all %}
        <input type="radio" id="batch{{ forloop.counter }}" name="batch" value="{{ batch.pk }}">
        <label for="batch{{ forloop.counter }}">
            {{ batch.batchNumber }}
            {% if batch.is_favorite %}
                <strong>selected as FAVORITE</strong>
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

<!--
<ul>
    {% for batch in product.batch_set.all %}
        <li>Associated batch, with number: {{ batch.batchNumber }}</li>
    {% endfor %}
</ul>
-->